apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: demo-policy
  namespace: dev
spec:
  podSelector:
    matchLabels:
      app: server
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          app: production
    - podSelector:
        matchLabels:
          run: client
    ports:
    - port: 80
      protocol: TCP
