apiVersion: v1
kind: Namespace
metadata:
  name: dev
  labels:
    app: dev
---
apiVersion: v1
kind: Namespace
metadata:
  name: staging
  labels:
    app: staging
---
apiVersion: v1
kind: Namespace
metadata:
  name: production
  labels:
    app: production

---
apiVersion: v1
kind: Namespace
metadata:
  name: production2
  labels:
    app: production2
---
apiVersion: v1
kind: Namespace
metadata:
  name: production3
  labels:
    app: production3
