apiVersion: v1
kind: Namespace
metadata:
  name: dev
  labels:
    app: dev
---
apiVersion: v1
kind: Namespace
metadata:
  name: staging
  labels:
    app: staging
---
apiVersion: v1
kind: Namespace
metadata:
  name: production
  labels:
    app: production
---
apiVersion: v1
kind: Namespace
metadata:
  name: ingress
  labels:
    app: ingress
---
apiVersion: v1
kind: Namespace
metadata:
  name: ingress2222
  labels:
    app: ingress2222
