
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-dev
  namespace: dev
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
  ingress:
    - from:
      - podSelector: {}
      - namespaceSelector:
          matchLabels:
            app: dev
            name: app-routing-system
  egress:
    - to:
      - namespaceSelector:
          matchLabels:
            kubernetes.io/cluster-service: "true"
        podSelector:
          matchLabels:
            k8s-app: kube-dns
      ports:
      - port: 53
        protocol: UDP
      - port: 53
        protocol: TCP
    - ports:
      - port: 445
        protocol: TCP
    - to:
      - ipBlock:
          cidr: 0.0.0.0/0
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-ingress
  namespace: app-routing-system
spec:
  podSelector:
    matchLabels:
      app: nginx-internal-0
  policyTypes:
    - Egress
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              app: dev
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/cluster-service: "true"
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - port: 53
          protocol: UDP
        - port: 53
          protocol: TCP